export const LOGIN = 'LOGIN'

export const REQUESTED_LOGIN = 'REQUESTED_LOGIN'
export const REQUESTED_LOGIN_SUCCEEDED = 'REQUESTED_LOGIN_SUCCEEDED'
export const REQUESTED_LOGIN_FAILED = 'REQUESTED_LOGIN_FAILED'

export const LOGOUT = 'LOGOUT'
